### ISSUE TITLE
Issue using Windows files system

### ISSUE THREAD

**Issue by navjinder** [tutorialzine/cute-files#1]
Hi I have installed cute files under mean stack on windows. The issue is the files path are now changed (windows based \ slash) which is giving error as it the script.js files assumes it to be a unix path. However, the links are fixed by changing the line 211
![cute-files-error](https://cloud.githubusercontent.com/assets/3472650/4443256/95eec682-47e6-11e4-9fba-1df763238873.PNG) 

But still file download issue persist. 

![cute-files-error-2](https://cloud.githubusercontent.com/assets/3472650/4443308/0ce41cc4-47e7-11e4-941b-f48e296168e6.PNG)

**Comment by martinaglv** [comment]
I finally had time to take a look at it today. The script now works under Windows by always using forward slashes. It seems to solve the problem. The fix is available on npm. 

Thank you for reporting this issue!
